/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaohei_java_lib_JNITest */

#ifndef _Included_com_xiaohei_java_lib_JNITest
#define _Included_com_xiaohei_java_lib_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaohei_java_lib_JNITest
 * Method:    test
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_xiaohei_java_lib_JNITest_test
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_xiaohei_java_lib_JNITest
 * Method:    test1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_xiaohei_java_lib_JNITest_test1
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_xiaohei_java_lib_JNITest
 * Method:    test2
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_xiaohei_java_lib_JNITest_test2
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
